### 阵列创建
array函数从常规Python列表或元组创建数组。


In [41]:
import numpy as np
a = np.array([2,3,4])
a


array([2, 3, 4])

In [42]:
a.dtype

dtype('int64')

In [43]:
b = np.array([1.2,  3.5, 5.1])
b.dtype

dtype('float64')

In [44]:
b = np.array([(1, 2, 3),(4, 5 , 6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
b.dtype

dtype('int64')

In [46]:
c = np.array([[3,4],[1,2]], dtype = float)
c

array([[3., 4.],
       [1., 2.]])

In [47]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones((2,3,4) , dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [49]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [50]:
np.arange(0,2,0.3) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [51]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [52]:
x = np.linspace(0, 2*pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [53]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

### 印刷阵列

In [57]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [58]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [59]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### 基本操作

In [65]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [66]:
c = a-b
c

array([20, 29, 38, 47])

乘方

In [67]:
b**2

array([0, 1, 4, 9])

下面这行代码是干啥的？

In [68]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

判断

In [69]:
a<25

array([ True, False, False, False])

与许多矩阵语言不同，乘积运算符*在NumPy数组中按元素进行操作。可以使用@运算符（在python> = 3.5中）或dot函数或方法执行矩阵乘积：

In [70]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

In [71]:
A*B

array([[2, 0],
       [0, 4]])

In [75]:
print(A.dot(B))
A@B

[[5 4]
 [3 4]]


array([[5, 4],
       [3, 4]])

某些操作（例如+=和）*=就位以修改现有数组，而不是创建一个新数组。

In [104]:
a = np.ones((2,3),dtype = int)
b = np.random.random((2,3))
a

array([[1, 1, 1],
       [1, 1, 1]])

In [98]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [103]:
b += a 
b

array([[1.01140352, 1.04833791, 1.82864832],
       [1.23896941, 1.2255363 , 1.14648249]])

此处注意，float+int可行，int+float会报错

In [105]:
a += b
a

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

当使用不同类型的数组进行操作时，结果数组的类型对应于更通用或更精确的数组（这种行为称为向上转换）。

In [115]:
a = np.ones(3,dtype = np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [116]:
b

array([0.        , 1.57079633, 3.14159265])

In [117]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [118]:
c.dtype.name

'float64'

In [119]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [120]:
d.dtype.name

'complex128'

sum(),min(),max()

In [ ]:
a = np.random.random((2,3))
a

In [122]:
a.sum()

4.417501726848943

In [124]:
a.max()

0.9025621792935841

In [125]:
a.min()

0.3597851426758729

In [129]:
b = np.arange(12).reshape(2,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

将每行元素相加

In [130]:
b.sum(axis = 0)

array([ 6,  8, 10, 12, 14, 16])

每列元素相加，然后取每列的最小值

In [133]:
b.min(axis = 1)

array([0, 6])

In [134]:
b.cumsum(axis = 1)

array([[ 0,  1,  3,  6, 10, 15],
       [ 6, 13, 21, 30, 40, 51]])

### 通用函数